name: example
description: Example using prefix provider
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  prefix_provider:
    path: ".."

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
